language: objective-c
osx_image: xcode9
cache:
  directories:
   - ReactNative/node_modules
   - Pods
before_install:
 - cd ReactNative
 - nvm install 8
 - node --version
install:
 - npm install
 - cd ..
 - travis_wait pod install
script:
 - xcodebuild -workspace ReactNativeRealmManualLink.xcworkspace -scheme ReactNativeRealmManualLink clean build
